name = "glm_vault"
version = "2.1.0"

description = "Read and write secrets to an encrypted file. Inspired by ansible's vault."
licences = ["Apache-2.0"]
repository = { type = "github", user = "toddg", repo = "glm_vault" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
tom = ">= 2.1.0 and < 3.0.0"
glm_encrypted_file = ">= 2.0.2 and < 3.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
